# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

Description: SNS Topic for drs-plan-automation pipeline and approval
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Application:
    Description: Application Name
    Type: String
    Default:  drs-plan-automation
  env:
    Type: String

Resources:
  DRSPlanAutomationPipelineSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for drs-plan-automation pipeline and approval
      TopicName: drs-plan-automation-pipeline

  DRSPlanAutomationSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for drs-plan-automation end users
      TopicName: !Sub "drs-plan-automation-${env}"

  DRSSolutionAutomationPlanSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref DRSPlanAutomationPipelineSNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Id: SSEAndSSLPolicy
        Statement:
          - Sid: PublishEvents
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sns:Publish
            Resource:
              - !Ref DRSPlanAutomationPipelineSNSTopic

Outputs:
  AWSConfigRequiredTagsSNSTopicArn:
    Value: !Ref DRSPlanAutomationPipelineSNSTopic
    Description: "SNS Topic for drs-plan-automation pipeline and approval"
    Export:
      Name: drs-plan-automation-pipeline-sns-topic-arn
