version: 0.2
phases:
  install:
    commands:
#      - apt-get -y update
      - gem install cfn-nag      
  build:
    commands:
      - chmod +x cfn/codebuild/ValidateTemplates/run-cfnnag.sh
      - /bin/bash cfn/codebuild/ValidateTemplates/run-cfnnag.sh
